### ISSUE TITLE
Investigate 43rd St. Oakland

### ISSUE THREAD

**Issue by migurski** [pelias/interpolation#19]
The even/odd switching in the western Emeryville section of 43rd St. is odd:

<img width="1263" alt="screen shot 2016-10-24 at 9 32 04 am" src="https://cloud.githubusercontent.com/assets/58730/19654362/c4c56bf2-99cc-11e6-9b09-b66e181223c4.png">

**Comment by missinglink** [comment]
this is due to the left most street segments being disjoined by the roundabouts.

the system contains 4 distinct line strings which were drawn in different directions (left-to-right or right-to-left) by their author, hence why the red (right side) differ per segment.

see: https://gist.github.com/anonymous/bdf311c2d3fe9161a34884f8c7e0610d

this in itself is not an issue, and per-segment search and interpolation will still work correctly.

if we can join the segments in to a single line string then we will be able to interpolate in the gaps between the line strings also.

I suspect the root cause is that the roundabouts don't have names, or are not tagged with the east-west road name.

@migurski are you familiar enough with the area to update OSM?

**Comment by missinglink** [comment]
see: https://github.com/pelias/pelias/wiki/Interpolation:-conflation#multiple-lines for a more visual explanation

**Comment by missinglink** [comment]
these are the roundabouts:

- http://www.openstreetmap.org/way/277235110
- http://www.openstreetmap.org/way/277235106

**Comment by migurski** [comment]
Yes, I can update these roundabouts!

**Comment by migurski** [comment]
http://www.openstreetmap.org/changeset/43179795#map=19/37.83339/-122.27865

**Comment by missinglink** [comment]
winning!

**Comment by missinglink** [comment]
I'm going to leave this open until we can get some 'fresh cuts' from valhalla and see if that worked.

**Comment by missinglink** [comment]
@migurski your OSM update has resolved the issue, thanks!

http://missinglink.embed.s3.amazonaws.com/43rd_oakland.png
