### ISSUE TITLE
interpolation seems to fail

### ISSUE THREAD

**Issue by woiza** [pelias/interpolation#195]
I am building europe with your docker files. It seams to me that interpolation fails since the the error and skip databases are large and address.db is very small:

ls -lah

total 17G
drwxr-xr-x  4 dataproject root        4.0K Apr 26 17:34 .
drwxrwxr-x 15 dataproject dataproject 4.0K Apr 24 15:08 ..
-rw-r--r--  1 dataproject root        304M Apr 26 19:23 address.db
drwxr-xr-x  2 dataproject root        4.0K Apr 19 12:08 builds
-rw-r--r--  1 dataproject root        9.9G Apr 26 19:23 conflate_oa.err
-rw-r--r--  1 dataproject root         92K Apr 26 19:23 conflate_oa.out
-rw-r--r--  1 dataproject root        2.3G Apr 26 19:24 conflate_oa.skip
-rw-r--r--  1 dataproject root        7.0K Apr 26 16:54 polyline.err
-rw-r--r--  1 dataproject root         30K Apr 26 17:30 polyline.out
-rw-r--r--  1 dataproject root        3.2G Apr 26 17:30 street.db
-rw-r--r--  1 dataproject root        1.4G Apr 26 17:34 street.db.gz
drwxr-xr-x  3 dataproject root        4.0K Apr 19 13:17 tmp

less conflate_oa.err
could not reliably parse housenumber 18Č
could not reliably parse housenumber 1Č
could not reliably parse housenumber 2Č

less polyline.err
street has no valid names, check your 0sv file:
q|psiBiie{r@kBbDkDtBqd@v@g\o@iL}D
street has no valid names, check your 0sv file:
kwwsiBcbi{r@bG|^yAv`@DfFrAtCby@bXzFu@pBoJ

Here is my complete pelias.json config:
https://github.com/dataBikeHsUlm/docker/blob/master/projects/europe/pelias.json

And docker compose:
https://github.com/dataBikeHsUlm/docker/blob/master/projects/europe/docker-compose.yml

What's wrong?

**Comment by missinglink** [comment]
Hi @woiza, are you seeing this warning in your logs?

https://github.com/pelias/polylines/blob/f6518a58fcf6881568129e57164799fe03ac02ae/docker_extract.sh#L23-L32

**Comment by woiza** [comment]
Hi @missinglink , I saw this warning and used Valhalla to extract polylines... But after that i got more RAM (64GB now) and used `pelias prepare polylines` again. RAM consumption did not go over 40GB, so I guess polylines are fine. This was about 2 weeks ago.
About 24 hours ago I did the following:

`pelias compose down`
`pelias compose up`
`pelias prepare interpolation`

`.../cmd/osm.js /data/interpolation/address.db /data/interpolation/street.db/` has not finished yet...

ls -lah /data/pelias-docker-compose/interpolation/
total 30G
drwxr-xr-x  4 dataproject root        4.0K May  6 07:10 .
drwxrwxr-x 15 dataproject dataproject 4.0K Apr 24 15:08 ..
-rw-r--r--  1 dataproject root        3.8G May  6 17:50 address.db
drwxr-xr-x  2 dataproject root        4.0K Apr 19 12:08 builds
-rw-r--r--  1 dataproject root         15G May  6 07:10 conflate_oa.err
-rw-r--r--  1 dataproject root        686K May  6 07:10 conflate_oa.out
-rw-r--r--  1 dataproject root        6.7G May  6 07:10 conflate_oa.skip
-rw-r--r--  1 dataproject root         56M May  6 17:50 conflate_osm.err
-rw-r--r--  1 dataproject root        570K May  6 17:50 conflate_osm.out
-rw-r--r--  1 dataproject root        7.0K May  5 17:32 polyline.err
-rw-r--r--  1 dataproject root         30K May  5 18:08 polyline.out
-rw-r--r--  1 dataproject root        3.2G May  5 18:09 street.db
-rw-r--r--  1 dataproject root        1.4G May  5 18:12 street.db.gz
drwxr-xr-x  3 dataproject root        4.0K Apr 19 13:17 tmp

Last stdout entries:
Mon May 6 03:30:30 UTC 2019 /data/openaddresses/de/he/city_of_frankfurtammain.csv
Mon May 6 03:30:58 UTC 2019 /data/openaddresses/nl/countrywide.csv
Mon May 6 04:33:43 UTC 2019 /data/openaddresses/dk/countrywide.csv
conflating openstreetmap

Looks better now, but I am not sure if everything is correct since .err and .skip are still large...
Have there been any changes since 26 April?

**Comment by missinglink** [comment]
The errors you posted are due to the 'c' symbol in `18Č` not being parsed as a unit number, this can be fixed by updating the parser to accommodate it.

The skip file lists all the addresses which the engine couldn't find a corresponding street for, so its fairly common that the names don't match for one reason or another.

Without knowing more I couldn't comment on the reasons that these files contain log lines.

All the changes made to the project are listed in the commit history on GitHub. Pull requests are linked in the commit history so you can cross-reference.

The core team do not currently test large extracts of the docker-compose projects, so we can't really comment on whether it used to work any differently in the past.

**Comment by missinglink** [comment]
What exactly is the issue you are reporting?

**Comment by woiza** [comment]
The issue is that I had hardly any addresses in address.db and street.db but it seams to be resolved since this time the interpolation command is still running and the databases are growing.

Is there anything I could do to speed this up? Load is less than 1.5 (4 CPUs).

Would it be much work to update the parser? I am building Europe and I guess there are many similar addresses and names in European countries. How can I help?

**Comment by missinglink** [comment]
Sorry for the short reply, I was on the run yesterday.

The parser is simple to update:
- https://github.com/pelias/interpolation/blob/master/lib/analyze.js#L116
- https://github.com/pelias/interpolation/blob/master/test/lib/analyze.js

Regarding the duration of the build, unfortunately it just takes a long time to build.

It because if the nature of the problem, it's taking 500+ million addresses and trying to match them using just a street name and lat/lon to a street database.

The easiest way to improve performance would be to parallelize the building of the address database.

In order to do this you could generate the street database once and then generate one address database per import (so one per openaddresses file).

You'd then need to merge the address databases, this should be easy because the streetdb foreign key references are the same, I can't remember the schema off the top of my head but I think there may be some other foreign keys to be careful of.

Once the address databases are merged you could then run the `interpolate vertices` step and you'd end up with the same database albeit in much less time.

Unfortunately I don't have time at the moment to parallelize the existing scripts but if you'd like to give it a shot I would be happy to provide guidance on how to do any of what I mentioned above.

**Comment by woiza** [comment]
Thanks for your answer. I will wait for it to finish and talk about parallelisation with my supervisor if we should take a shot at it or just leave it as it is (once I know how long it takes). At the moment I do not know if there will be a requirement to reimport Europe completely again.
Let's say I have new/updated data (openaddresses, whosonfirst, geonames and openstreetmaps) for a single country (e.g. Belgium) or just a region, can I use the usual pelias prepare and import steps with these files? Will the databases and Elasticsearch index be "consistent" afterwards or how should I do this?

**Comment by nilsnolde** [comment]
In short: you'll have to create a new index for updated datasets. You can import that on a separate ES instance, dump the index and load them to your production ES. Make sure to use an index alias in your `pelias.config`, then you'll never have to update the index name in there and just make a single call to ES adding the alias to your new index and removing it from the old.

General questions like that are better asked on their [Gitter channel](https://gitter.im/pelias/pelias).

**Comment by woiza** [comment]
thanks @nilsnolde
will try that.

**Comment by missinglink** [comment]
@woiza if you'd like a copy of the global planet interpolation build we produce for geocode.earth cloud then send us an email.

It would probably be pretty quick and easy to remove all non-european data from the global build and use that instead.

We're not currently providing it for download due to the costs of generating and hosting it.

https://geocode.earth/consultancy#contactus

**Comment by woiza** [comment]
@missinglink awesome! I just sent an email to hello@...

**Comment by shekoufa** [comment]
Hey team! 

My team is having kind of a similar issue as @woiza. We are trying to build the entire planet from scratch again as we realized that in our previous attempt we had a problem with prepare interpolation failing silently and it went without notice. Basically, in our last attempt the street.db size after interpolation was done was only 32 KB!! and then address.db file was 16 KB! This time around our prepare interpolation has been running for some 16 hours and then two files mentioned above are at 7.3 GB and 12 GB respectively. So, things apparently are going better this time. However, what that worries me is the size of the conflate_oa.err and conflate_oa.skip files. 
12G	        address.db
4.0K	        builds
35G	        conflate_oa.err
1.2M	conflate_oa.out
12G	        conflate_oa.skip
104K	polyline.err
100K	polyline.out
7.3G	        street.db
3.6G	street.db.gz

Does this huge amount of error parsing addresses and skipping them sound reasonable for a planet build? Would it cause the performance to suffer due to missing data? Basically, it would be amazing to know roughly how big the address.db and street.db files should be for a planet build.

**Comment by missinglink** [comment]
I spent a lot of time over the last two weeks improving the performance and stability of the interpolation builds in https://github.com/pelias/interpolation/pull/244

I was able to complete a full-planet build in ~4 days using that code, can you please retry with the latest code and open a new issue if need be.

**Comment by MALKARAJ** [comment]
Hi @missingLing can you please guide me on how to parallelize the pelias prepare interpolation  build for the whole planet
