### ISSUE TITLE
'/data/openstreetmap/*.osm.pbf': No such file or directory

### ISSUE THREAD

**Issue by stefanocudini** [pelias/interpolation#205]
I think it is wrong... beacause in many cases pbf files.. isn't named with tail *.osm.pbf

ls: cannot access '/data/openstreetmap/*.osm.pbf': No such file or directory

it would be a good thing if he only looked for ***.pbf files**

**Comment by orangejulius** [comment]
Interesting. I think the idea is that since the pbf format itself is quite generic, it's important to clarify that only OSM PBF extracts are supported.

All the downloads from Geofabrik and planet.openstreetmap.org use the `.osm.pbf` extension. Do you have any examples of OSM PBF sources that don't use the `.osm.pbf` extension?

**Comment by missinglink** [comment]
I'd be fine with relaxing this to just `*.pdf`, I sometimes forget to add the 2-part extension and I think it'll avoid more errors than it causes.

**Comment by orangejulius** [comment]
We (finally) support `*.pbf` files as of https://github.com/pelias/interpolation/pull/269

**Comment by stefanocudini** [comment]
great!
