### ISSUE TITLE
address.db is not populating for openaddresses

### ISSUE THREAD

**Issue by pravink** [pelias/interpolation#227]
Hey team! 

I am trying to build the address.db from openaddresses using conflate_oa.sh but it outputs below in .out file 
```
0       0/sec
0       0/sec
0       0/sec
0       0/sec

```
and .skip file got few address in it.
and the address.db file is only 12KB, so suspecting something is not correct.

The street db has imported successfully. 
`3.1G Nov 20 07:06 street.db `

I can see the csv files are getting concatenated and sorted as well but still getting nothing in the address.db.

Thanks,
Pravin!

**Comment by pravink** [comment]
Hello everyone, does anyone faced similar issue while preparing address db?

**Comment by missinglink** [comment]
Hi @pravink here's a couple of things you can check:

**Are you using your own `polylines` data in the `street.db`?**
If so please ensure that the [encoding is set correctly](https://github.com/pelias/polylines#generating-your-own-data) otherwise it will fail to associate streets with addresses, if this is the case you will get the same error for `osm` imports as you do for `oa`.
You confirm this issue by decoding one the entries in your `address.db` using this tool (with the `polyline6` checkbox enabled) http://valhalla.github.io/demos/polyline/, it should decode correctly to a linestring coterminous to a street on the basemap.

**The .skip file should contain additional information**
This file is used to log errors when conflating the `street.db` with `polyline` data, can you post some of the errors so we can see what the system is reporting in this case?

**Comment by pravink** [comment]
Hi @missinglink,

Thanks for your response. 

Yes it is an encoding issues.. after re encoding it worked... 

but I am seeing lot of errors like below while preparing address.db using -  node cmd/oa address.db street.db

could not reliably parse housenumber 1/24
could not reliably parse housenumber 2/24
could not reliably parse housenumber 2-6
could not reliably parse housenumber 2A/2
could not reliably parse housenumber 2B/2
could not reliably parse housenumber 2C/2

does it mean its skipping from adding it to address.db?

**Comment by missinglink** [comment]
> does it mean its skipping from adding it to address.db?

Yes, lines in the skip file indicate records that's were skipped from the import due to an error, they don't end up in the database.

This particular error is caused by the algorithm not being to reliably understand which side of the / is the house number and which is the unit number.

I think this could be improved and I would be happy to review a PR to the analyze function to fix this if you can do it reliably for addresses internationally.

Either way it's likely not a big deal as the interpolation can usually discard some addresses with a range and yet still reliably recreate them based off neighbors.

**Comment by pravink** [comment]
@missinglink Thanks for your reply. I will spend sometime during the Christmas break and once its working I will raise a PR for it.
