### ISSUE TITLE
Hard-coded GeocodeEarth API key

### ISSUE THREAD

**Issue by tungleduyxyz** [pelias/interpolation#283]
Hi, I see this key is hard-coded not sure why, can anyone give me some advice to change this key in the docker file
https://github.com/pelias/interpolation/blob/dc71f4bed61a94fc5527aa2bea3ee22fb602d709/demo/index.html#L55

**Comment by missinglink** [comment]
Hi @tungleduyxyz, the host is also hardcoded here https://github.com/pelias/interpolation/blob/dc71f4bed61a94fc5527aa2bea3ee22fb602d709/demo/index.html#L61 and the Jawg key we were donated for demos.

I guess we didn't really foresee the need to make this configurable, the original goal was to have a demo link available on the github repo:

<img width="400" alt="Screenshot 2021-11-15 at 17 20 25" src="https://user-images.githubusercontent.com/738069/141816901-708af29f-c31b-4473-a1da-a409e7c7e1a1.png">

What would you like to do? Link to your own instance of pelias/interpolation?

**Comment by orangejulius** [comment]
Yeah, maybe we can set up some _very_ basic templating for the demo page. The code to serve it is here, it's just a static page rendered by [Express](https://expressjs.com/):

https://github.com/pelias/interpolation/blob/3564ca99daa16d9852de6b73d90a033435ddec80/cmd/server.js#L215-L216

The API key that's currently hardcoded was once used across all our demos and the Pelias Compare app. However, due to abuse we have to periodically rotate that key. It didn't help that the same key was used by anyone and everyone setting up their own Interpolation service and using the demo locally.

It would be nice if we could provide a default demo key that was specific to the interpolation service, but also let people override it. We at Geocode Earth would likely use that to ensure the API key used by our own instance of the demo that Peter mentioned was always working.

**Comment by tungleduyxyz** [comment]
Yes, it makes sense @orangejulius. For the current version, I need to build the demo myself because the key doesn't work. So, it will be better if I can register in GeocodeEarth, get the free trial key, and see how it work in the demo.
